AWSTemplateFormatVersion: 2010-09-09
Description: Reusable Template for WorldPress-EC2-Instance

 # Define Parameters
Parameters:
  # Define AMImage ID
  WPImageID:
    Type: String
    Default: 'ami-00e87074e52e6c9f9'
    Description: Enter Image ID
  # Define Instance Type
  InstanceType:
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.micro
      - t2.nano
  
  # Define Subnet ID
  SubnetID:
    Type: String
    Default: 'subnet-01318110118aa69e7'
    AllowedValues:
      - 'subnet-01318110118aa69e7'
    Description: Enter Subnet ID

  # WP Security Group ID
  WPSecurityGroupID:
    Type: String
    Default: 'sg-0eb52bb384864f891'
    Description: Enter Security Group ID
  #  Define SSHKeyName
  SSHKeyName:
    Type: String
    Default: 'MyMacKey'
    Description: Enter Your KeyPair Name
  # Required Tags
  EC2Name:
    Type: String
    Default: 'Centos-7'
    Description: Enter Name for Instance
  # Team Key
  TeamTagKey:
    Type: String
    Default: Team

  # Team Value
  TeamTagValue:
    Type: String
    Default: Infra

  # Env Key
  EnvTagKey:
    Type: String
    Default: Env

  # Env Value
  EnvTagValue:
    Type: String
    Default: dev

# Define Resources
Resources:
  # EC2-Wordpress 
  WPInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref WPImageID
      InstanceType: !Ref InstanceType
      SecurityGroupIds:
        - !Ref WPSecurityGroupID
      SubnetId: !Ref SubnetID
      KeyName: !Ref SSHKeyName
      Tags:
        - Key: !Ref EC2Name
          Value: !Ref TeamTagValue
        - Key: !Ref TeamTagKey
          Value: !Ref TeamTagValue
        - Key: EnvTagKey
          Value: !Ref EnvTagValue

# Define Outputs
Outputs:
  InstancePublicIp:
    Description: Instance Public IP Address
    Value: !GetAtt WPInstance.PublicIp