AWSTemplateFormatVersion: "2010-09-09"
Resources:
  MyEc2Instance: 
    Type: "AWS::EC2::Instance"
    Properties:
      InstanceType: "t2.micro"
      ImageId: "ami-02354e95b39ca8dec"
      SubnetId:
      Tags:
        - Key: "Name"
          Value: "MyEC2Instance"

   