AWSTemplateFormatVersion: "2010-09-09"
Resources:
  MyVPC:
    Description: "VPC"
    Type: AWS::EC2::VPC
    Properties: 
      CidrBlock: " "
      EnableDnsHostnames: true
      EnableDnsSupport: true
      InstanceTenancy: "default"
      Tags: 
        - Key: "Name"
          Value: "MyVPC"
    Type: AWS::EC2::VPCCidrBlock
    Properties: 
      AmazonProvidedIpv6CidrBlock: 
      CidrBlock: 
      VpcId: 
    
