AWSTemplateFormatVersion: 2010-09-09
Resources:
  #Resource 1  
  # Security Group EC2 Instance
  MySecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "CloudFormationSecurityGroup"
      GroupName: "" #Enter GroupName
      VpcId: "" #Enter VPC ID
      SecurityGroupIngress:
      - CidrIp: "0.0.0.0/0"
        FromPort: 22
        ToPort: 22
        IpProtocol: "tcp"
        Description: "SSH from 0.0.0.0/0"
      - CidrIp: "0.0.0.0/0"
        FromPort: 80
        ToPort: 80
        IpProtocol: "tcp"
        Description: "HTPP from 0.0.0.0/0"

  #Resource 2
  # EC2 Instance
  MyEc2Instance:
    Type: AWS::EC2::Instance
    DependsOn: MySecurityGroup #the previous Resource1 is specified
    Properties:
      ImageId: "ami-02354e95b39ca8dec"
      InstanceType: "t2.micro"
      SubnetId: ""  #Enter Subnet ID
      SecurityGroupIds:
        - Ref: "MySecurityGroup"
      KeyName: "" #Enter KeyPair Name
      Tags:
        - Key: "Name"
          Value: "MyEC2Instance"
        - Key: "Team"
          Value: "DevOps"
        - Key: "Env"
          Value: "Dev"