AWSTemplateFormatVersion: 2010-09-09
Resources:
  MySecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "Security group for EC2"
      GroupName: "SG-EC2"
      SecurityGroupIngress:
        - IpProtocol: "tcp"
          CidrIp: "0.0.0.0/0"
          FromPort: 22
          ToPort: 22
      Tags:
        - Key: "GroupName"
          Value: "SG-EC2"

 