AWSTemplateFormatVersion: 2010-09-09

# Resources Section
Resources:
  Type: AWS::EC2::SubnetRouteTableAssociation
  Properties: 
    RouteTableId: String
    SubnetId: String

  # Subnet 1 - Public
  MySubnet:
    Type: AWS::EC2::Subnet
    Properties: 
      AvailabilityZone: "us-east-2a"
      CidrBlock: "10.0.1.0/24"
      VpcId: ""
      Tags:
        - Key: "Name"
          Value: "My-sub"

  # RouteTable - Public
  MyRouteTable:
    Type: AWS::EC2::RouteTable
    Properties: 
      VpcId: ""