AWSTemplateFormatVersion: 2010-09-09

# Resources Section
# Subnet Route Table Association
Resources:
  MySubnetRouteTableAsseciation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref MyRouteTable #Ref returns the value of MyRouteTable
      SubnetId: !Ref MySubnet #Ref returns the value of MySubnet
  # Subnet 1 - Public
  MySubnet:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: "" 
      CidrBlock: ""
      VpcId: "" # enter VPC ID
      Tags:
        - Key: "Name"
          Value: "My-sub"
  # RouteTable - Public
  MyRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: "" # enter VPC ID