AWSTemplateFormatVersion: 2010-09-09

# Public Subnet
Resources:
  MySubnet:
    Type: AWS::EC2::Subnet
    Properties: 
      AvailabilityZone: "us-east-2a"
      CidrBlock: ""
      VpcId: "" #enter VPC ID
      Tags:
        - Key: "Name"
          Value: "My-sub"