AWSTemplateFormatVersion: 2010-09-09
Resources:
  MyTaggedBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: "cloudformation-aina-test-bucket2"
      VersioningConfiguration:
        Status: Enabled 
      Tags: 
        - Key: "Team"
          Value: "Dev"
        - Key: "Evn"
          Value: "Test"